### ISSUE TITLE
Positioning for overlay

### ISSUE THREAD

**Issue by panchofrank** [ghettovoice/vuelayers#154]
Hello,
My vl-overlay seems to ignore the positioning attribute in my application.  I also tried changing the value for the positioning in the demo app but it also seems to be ignored there.  What am I doing wrong?

<img width="667" alt="Screenshot 2019-04-17 at 16 16 03" src="https://user-images.githubusercontent.com/9303099/56295202-b1be3a00-612c-11e9-9014-a611c08f979c.png">

**Comment by ghettovoice** [comment]
Hi @panchofrank ,
check css styles that are applied to the popup container. 
In the demo I use absolute position, and this prevents `positioning` property to work correctly

```css
.vld-demo-app .feature-popup {
    position: absolute;
    left: -50px;
    bottom: 12px;
    width: 20em;
    max-width: none;
}
```
